### PR TITLE
Update example in HybridGibbs

### LINKED ISSUE #511: Update example in docstring of HybridGibbs
https://github.com/CUQI-DTU/CUQIpy/blob/98a74d508a1aa4659a6176a0126a90371a6be581/cuqi/experimental/mcmc/_gibbs.py#L92 should be updated to  something like
```python
sampler.sample(200)
sampler.warmup(1000)
samples = sampler.get_samples()
```

## Definition of Done
- [x] Correct use if sampler API implemented in example
- [ ] Change is reviewed and approved.

### PR DESCRIPTION
**Pull request by nabriis**
Closes #511

### CODE REVIEW

**Review by chaozg — APPROVED** [review]
LGTM!

**Comment by jakobsj** [comment]
Why the change from `square` to `sinc`?

**Comment by nabriis** [comment]
> Why the change from `square` to `sinc`?

matches better with the GMRF prior. No idea why it was square before.

**Review by jakobsj — APPROVED** [review]
OK, sounds good - approving!

**Pull request merged**
