### PR TITLE
Sprint13 allow model other parameter names

### LINKED ISSUE #112: Allow models to actually work with other parameter names than x
Currently this kind of code fails

``` Python
import cuqi
y = cuqi.distribution.GaussianCov(0, 1)
model_s = cuqi.model.Model(lambda s: s, 1, 1)
model_y = model_s(y) # Switch name

# Only x works atm
assert model_s(s=1) == 1 
assert model_y(y=1) == 1
```

### PR DESCRIPTION
**Pull request by nabriis**
Closes #112, #57

### CODE REVIEW

**Review by amal-ghamdi — COMMENTED** [review]
Thank you @nabriis for adding this great feature and the tests! I have only one comment. I was confused about the documentation of the utility function: 
```python
def get_non_default_args(func):
""" Returns the non-default arguments and kwargs from a callable function"""
```

While for example in the test here we have:
```python
model_z._non_default_args == ['z'] # the keyword argument not_used does not show up
```

does `get_non_default_args` actually returns the kwargs?

**Comment by nabriis** [comment]
> Thank you @nabriis for adding this great feature and the tests! I have only one comment. I was confused about the documentation of the utility function:
> 
> ```python
> def get_non_default_args(func):
> """ Returns the non-default arguments and kwargs from a callable function"""
> ```
> 
> While for example in the test here we have:
> 
> ```python
> model_z._non_default_args == ['z'] # the keyword argument not_used does not show up
> ```
> 
> does `get_non_default_args` actually returns the kwargs?

Great question. It returns the arguments and keyword arguments that do not have a default value.

This is what was chosen a good while ago. Its important for partial functions, which are made by redefining a function with some partially specified arguments through the default mechanism. We use it when conditioning but only paetly specifying arguments of a function

**Comment by amal-ghamdi** [comment]
> > Thank you @nabriis for adding this great feature and the tests! I have only one comment. I was confused about the documentation of the utility function:
> > ```python
> > def get_non_default_args(func):
> > """ Returns the non-default arguments and kwargs from a callable function"""
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > While for example in the test here we have:
> > ```python
> > model_z._non_default_args == ['z'] # the keyword argument not_used does not show up
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > does `get_non_default_args` actually returns the kwargs?
> 
> Great question. It returns the arguments and keyword arguments that do not have a default value.
> 
> This is what was chosen a good while ago. Its important for partial functions, which are made by redefining a function with some partially specified arguments through the default mechanism. We use it when conditioning but only partly specifying arguments of a function


Thank you @nabriis for the explanation. I am still not quite sure what  a keyword arguments that do not have a default value mean. Can you provide a simple example?

**Comment by nabriis** [comment]
> > > Thank you @nabriis for adding this great feature and the tests! I have only one comment. I was confused about the documentation of the utility function:
> > > ```python
> > > def get_non_default_args(func):
> > > """ Returns the non-default arguments and kwargs from a callable function"""
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > While for example in the test here we have:
> > > ```python
> > > model_z._non_default_args == ['z'] # the keyword argument not_used does not show up
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > does `get_non_default_args` actually returns the kwargs?
> > 
> > 
> > Great question. It returns the arguments and keyword arguments that do not have a default value.
> > This is what was chosen a good while ago. Its important for partial functions, which are made by redefining a function with some partially specified arguments through the default mechanism. We use it when conditioning but only partly specifying arguments of a function
> 
> Thank you @nabriis for the explanation. I am still not quite sure what a keyword arguments that do not have a default value mean. Can you provide a simple example?

Yes, sorry for the confusion!

``` python 
def func(x, y, z=5):
    pass
```
Here x and y are non default arguments, and z is a default argument (because we do not have to set it)

**Review by amal-ghamdi — APPROVED** [review]
Thank you, it is just that I would think keyword arguments are always supplied with default values. But may I'm missing something. 

LGTM!

**Review by jakobsj — APPROVED** [review]
Nice fix. I read through the code but didn't run it. Appears to achieve what it claims to do. Great to see such comprehensive testing of the desired behavior :)

**Pull request merged**
