### PR TITLE
add ability to store run diagnostics for inspection (NUTS sampler)

### LINKED ISSUE #261: Suggested feature: Add ability to inspect NUTS running diagnostics
Allow user to look into tree size and step size in each NUTS iteration

Consider `sampler` is a nut sampler, the user can plot

```
fig, ax= plt.subplots(1,2, figsize=(8,3))
plt.suptitle('N='+ str(N) +', Nb='+ str(Nb) + ', max_depth='+ str(sampler.max_depth))
plt.sca(ax[0])
plt.plot(sampler.iteration_list, sampler.num_tree_node_list, label='num_tree_node')
plt.legend()
plt.sca(ax[1])
plt.plot(sampler.iteration_list, sampler.epsilon_list, label='epsilon')
plt.plot(sampler.iteration_list, sampler.epsilon_bar_list, label='epsilon_bar')
plt.legend()
```

Image

Image

### PR DESCRIPTION
**Pull request by amal-ghamdi**
closes #261

### CODE REVIEW

**Comment by amal-ghamdi** [comment]
We can add demo/test if we are going with merging this.

**Review by nabriis — CHANGES_REQUESTED** [review]
I think it is a nice feature to add diagnostics to the NUTS sampler (and perhaps smart diagnostics) on all samplers. We need to discuss how to implement a user interface for this. One idea is for the sampler to have this diagnostics inside it. This makes sense in particular after the #145 is completed. 

However, after sampling it would also be useful to have information about the origin of the Samples and how the sampling went in the Samples object. 

Something to think about and discuss at our next meeting

**Review by nabriis — APPROVED** [review]
Looks good to me. Perhaps create an issue to track future work on creating an user facing interface for diagnostics of samplers.

**Comment by amal-ghamdi** [comment]
Thank you @jakobsj and @nabriis for the review and the approval. I made few changes since your review to add documentation, and changed the place where epsilon and epsilon_bar are recorded so that the step size corresponds to the iteration at which the step size was used (it was off by one).

**Review by jakobsj — APPROVED** [review]
Excellent - documentation looks good and good to hear your caught it being off by one.

**Review by nabriis — APPROVED** [review]

**Comment by amal-ghamdi** [comment]
Thank you @jakobsj and @nabriis for the rearview, I created an issue for diagnostics user interface #274 and mentioned it in the sampler rework issue #34. Merging

**Pull request merged**
