### PR TITLE
Initial version of pip release code

### LINKED ISSUE #97: Release CUQIpy on pip
We should release CUQIpy on pip under some pip account. Looks like you can't really have an orginization, but we could create a CUQIpy pip account perhaps, using e.g. email of Jakob.

See PR #54

### PR DESCRIPTION
**Pull request by nabriis**
Closes #97. 

Test release will be put here https://test.pypi.org/project/cuqipy/ (version is auto generated)

We can add the test release manually as follows
```
python -m build
twine check dist/*
twine upload -r testpypi dist/*
```

#100  adds automatic release.

- Added [pyproject.toml](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/) to configure pip release. This is becoming the new standard. Also added setup.py for backward compatibility.
- Added automatic version handling via git tags using [versioneer](https://github.com/python-versioneer/python-versioneer). This tool is also used by NumPy, SciPy and a number of other packages. Recently added support for the new .toml standard.

To be added after we verify the pip test release (in a new PR)
- GitHub action triggered on when a "release tag" is added to publish to Pypi

Edit:
You can test install by running the following code (in a new conda environment) in root directory:
```
pip install .
```

`_version.py` is an auto generated file from versioneer that needs to be checked in to version control.

### CODE REVIEW

**Comment by amal-ghamdi** [comment]
Brilliant @nabriis. Thank you for putting the pip release together. 

This is really exiting :). I tested the install using the instructions you provided above and everything seems to work smoothly :). I tested some cuqi code that uses Arviz just to double check the dependencies and it is working. 

I have just have a question and a comment for now. 

- This is a pypi question, can you please just help me understand what does test indicates in `https://test.pypi.org/project/cuqipy/`?  Is this something temporary? will we be using something like `https://pypi.org/project/cuqipy/` later on?
- In the page `https://test.pypi.org/project/cuqipy/ ` I noticed the images does not appear and I was wondering if the left column content can be reduced.

**Comment by nabriis** [comment]
> Brilliant @nabriis. Thank you for putting the pip release together.
> 
> This is really exiting :). I tested the install using the instructions you provided above and everything seems to work smoothly :). I tested some cuqi code that uses Arviz just to double check the dependencies and it is working.
> 
> I have just have a question and a comment for now.
> 
> * This is a pypi question, can you please just help me understand what does test indicates in `https://test.pypi.org/project/cuqipy/`?  Is this something temporary? will we be using something like `https://pypi.org/project/cuqipy/` later on?
> * In the page `https://test.pypi.org/project/cuqipy/ ` I noticed the images does not appear and I was wondering if the left column content can be reduced.

Hi @amal-ghamdi, Great questions!

1. Test pypi is a mirror of pypi, but for testing purposes. We can use it to automatically run publish testing on any commit to main, but only publish the actual version to pypi.
2. Yes I also saw that the license file is formatted is an odd way. Not sure how to fix that.

**Comment by amal-ghamdi** [comment]
> > Brilliant @nabriis. Thank you for putting the pip release together.
> > This is really exiting :). I tested the install using the instructions you provided above and everything seems to work smoothly :). I tested some cuqi code that uses Arviz just to double check the dependencies and it is working.
> > I have just have a question and a comment for now.
> > 
> > * This is a pypi question, can you please just help me understand what does test indicates in `https://test.pypi.org/project/cuqipy/`?  Is this something temporary? will we be using something like `https://pypi.org/project/cuqipy/` later on?
> > * In the page `https://test.pypi.org/project/cuqipy/ ` I noticed the images does not appear and I was wondering if the left column content can be reduced.
> 
> Hi @amal-ghamdi, Great questions!
> 
> 1. Test pypi is a mirror of pypi, but for testing purposes. We can use it to automatically run publish testing on any commit to main, but only publish the actual version to pypi.
> 2. Yes I also saw that the license file is formatted is an odd way. Not sure how to fix that. But we can fix it in a later version and all subsequent versions will have better formatting on the left column.

Thank you for the clarification!

**Review by amal-ghamdi — APPROVED** [review]
Great!

**Review by jakobsj — APPROVED** [review]

**Pull request merged**
