### PR TITLE
Sprint20 enable nb in uq

### LINKED ISSUE #262: Enable passing Nb to BP.UQ

### PR DESCRIPTION
**Pull request by amal-ghamdi**
closes #262

### CODE REVIEW

**Review by nabriis — APPROVED** [review]
LGTM. Thanks for adding tests also

**Comment by amal-ghamdi** [comment]
> LGTM. Thanks for adding tests also

Thank you @nabriis for your review!
Just wanted to let you know that I just updated the Nb printing format to show part of percent (e.g. prints 0.2%  burn-in instead of rounding to integer and print 0% burn-in)

**Review by jakobsj — APPROVED** [review]
Looks great, thanks for adding this feature!

**Comment by amal-ghamdi** [comment]
> Looks great, thanks for adding this feature!

Thank you @jakobsj for your review! I'm merging this PR

**Pull request merged**
